"""
Initial Django Migration for Moodify Music Application

This migration creates the core database schema for the music recommendation system.
Generated by Django 5.0.6 on 2024-08-01 16:04

Database Tables Created:
- music_mood: Stores mood categories (Happy, Sad, Energetic, etc.)
- music_profile: User profiles with mood preferences
- music_song: Music library with mood associations
- music_usermood: User mood history tracking

Dependencies:
- Django's built-in User model for authentication
"""

# Generated by Django 5.0.6 on 2024-08-01 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initial database migration for Moodify music application.
    
    Creates the foundational models for mood-based music recommendations:
    - Mood categories for music classification
    - User profiles with mood preferences
    - Song library with mood associations
    - User mood interaction tracking
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create Mood model for music categorization
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        # Create Profile model for user preferences
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.mood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # Create Song model for music library
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(blank=True, max_length=100, null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('mood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.mood')),
            ],
        ),
        # Create UserMood model for interaction tracking
        migrations.CreateModel(
            name='UserMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.mood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
