"""
Django Database Migrations Package

This package contains Django database migration files that define the schema
evolution for the Moodify music application models.

Migration Files:
    - 0001_initial.py: Initial database schema creation
    - 0002_alter_mood_options_alter_profile_options_and_more.py: Model updates
    
These migrations are automatically generated by Django when models are modified
and should be applied using 'python manage.py migrate'.
"""
